---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
jobs:
  test:
    parameters:
      ruby_type:
        type: string
        default: ruby
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.3.10
      rails_version:
        type: string
    docker:
      - image: cimg/<< parameters.ruby_type >>:<< parameters.ruby_version >>-browsers
      - image: samveralabs/fcrepo3:latest
    environment:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      RACK_ENV: test
      RAILS_ENV: test
      RAILS_VERSION: << parameters.rails_version >>
      SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      RUBY_TYPE: << parameters.ruby_type >>
    steps:
      - attach_workspace:
          at: ~/
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: rubydora
      - run:
          name: Run RSpec
          command: |
            mkdir /tmp/test-results
            bundle exec rake docker:spec
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

workflows:
  version: 2
  ci:
    jobs:
      # Rails 7.2
      - test:
          name: "ruby3-3_rails7-2"
          ruby_version: 3.3.5
          rails_version: 7.2.1
      - test:
          name: "ruby3-2_rails7-2"
          ruby_version: 3.2.5
          rails_version: 7.2.1
      - test:
          name: "ruby3-1_rails7-2"
          ruby_version: 3.1.6
          rails_version: 7.2.1
      # Rails 7.1
      - test:
          name: "ruby3-3_rails7-1"
          ruby_version: 3.3.5
          rails_version: 7.1.4
      - test:
          name: "ruby3-2_rails7-1"
          ruby_version: 3.2.5
          rails_version: 7.1.4
      - test:
          name: "ruby3-1_rails7-1"
          ruby_version: 3.1.6
          rails_version: 7.1.4
      # Rails 7.0
      - test:
          name: "ruby3-3_rails7-0"
          ruby_version: 3.3.5
          rails_version: 7.0.8.4
      - test:
          name: "ruby3-2_rails7-0"
          ruby_version: 3.2.5
          rails_version: 7.0.8.4
      - test:
          name: "ruby3-1_rails7-0"
          ruby_version: 3.1.6
          rails_version: 7.0.8.4

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main

    jobs:
      # Rails 7.2
      - test:
          name: "ruby3-3_rails7-2"
          ruby_version: 3.3.5
          rails_version: 7.2.1
      - test:
          name: "ruby3-2_rails7-2"
          ruby_version: 3.2.5
          rails_version: 7.2.1
      - test:
          name: "ruby3-1_rails7-2"
          ruby_version: 3.1.6
          rails_version: 7.2.1
      # Rails 7.1
      - test:
          name: "ruby3-3_rails7-1"
          ruby_version: 3.3.5
          rails_version: 7.1.4
      - test:
          name: "ruby3-2_rails7-1"
          ruby_version: 3.2.5
          rails_version: 7.1.4
      - test:
          name: "ruby3-1_rails7-1"
          ruby_version: 3.1.6
          rails_version: 7.1.4
      # Rails 7.0
      - test:
          name: "ruby3-3_rails7-0"
          ruby_version: 3.3.5
          rails_version: 7.0.8.4
      - test:
          name: "ruby3-2_rails7-0"
          ruby_version: 3.2.5
          rails_version: 7.0.8.4
      - test:
          name: "ruby3-1_rails7-0"
          ruby_version: 3.1.6
          rails_version: 7.0.8.4
